Sale Fragment
namdangdev267/fresher pull request #10
Opened 2022-03-13 10:44 UTC by BaoNguyen068

2022-03-16 08:22 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/BillsAdapter.kt
> +        return ViewHolder(v)
// Viết ngắn lại thôi ông
        return ViewHolder(LayoutInflater.from(parent).inflate(R.layout.item_list_bill, parent, false))

2022-03-16 09:21 UTC, B-0625 requested changes

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/ProductSelectedAdapter.kt
> +            itemView.findViewById<TextView>(R.id.tvProductId).text = selectedProducts.product.id
thừa line này đúng không

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/ProductSelectedAdapter.kt
> +                tvAmount.text = selectedProducts.amonut.toString()
tại sao lại cần setText cho `tvAmount` ở đây nhỉ, sau khi callback `updateTotalPrice` ra ngoài -> gọi lại `notifyDataSetChanged()` thì nó tự được bind lại mà

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/ProductSelectedAdapter.kt
> +                    tvAmount.text = selectedProducts.amonut.toString()
Tương tự

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/ProductSelectedAdapter.kt
> +                    var tost = Toast.makeText(
Nên viết hàm showToast thành hàm chung hoặc sử dụng extension function

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/ReceiverViewAdapter.kt
> +                clickView(item)
tại sao lại gọi callback clickView ở đây nhỉ

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/ReceiverViewAdapter.kt
> +                item.hint=edReceiver.text.toString()
`Ctrl + Alt + L` để format code mỗi lần sửa file nhé

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/adapters/ViewPager2Adapter.kt
> +class ViewPager2Adapter(fragment: ShipInforFragment) : FragmentStateAdapter(fragment) {
để param constructor là Fragment thường thôi để còn dùng chỗ khác nữa được chứ ông, thằng `ShipInforFragment` implement Fragment mà

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/BillDetailFragment.kt
> +    var viewModel: ShareViewModel?= null
dùng kotlin ktx để khai báo viewModel bằng lazy cho tiện nhé

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/BillDetailFragment.kt
> +        listFromSale = getDataFromSaleFragment()
tách hàm ra

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/BillDetailFragment.kt
> +        for (i in listFromSale) {
i dùng để đặt cho biến index chạy thôi nhé, object thì đặt tên đúng kiểu

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/BillDetailFragment.kt
> +        configListSelectedItem(listFromSale, view)
`listFromSale` là biến bên ngoài rồi mà, cần gì truyền vào nữa

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/BillDetailFragment.kt
> +            activity?.onBackPressed()
Như này nếu thay đổi list ở màn BillDetail back lại thì có cập nhật được dữ liệu bên kia không

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/BillsFragment.kt
> +        rcv.layoutManager=LinearLayoutManager(view.context)
format code

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/BillsFragment.kt
> +            val adapter = BillsAdapter(it)
sao lại khởi tạo adapter và set trong observe thế?

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/PackageFragment.kt
> +
.

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/PackageFragment.kt
> +        adapter.notifyDataSetChanged()
vừa khởi tạo xong sao đã phải notifyDataSetChanged, căng thẳng thế

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/RecipientFragment.kt
> +    private var receiver = Receiver("","","","","","","","","")
để default argument cho class nhé

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/RecipientFragment.kt
> +        adapter.notifyDataSetChanged()
như trên

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/RecipientFragment.kt
> +        it as ShippingView.TouchTextView
dòng này để làm gì thế

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/RecipientFragment.kt
> +        }
logic đoạn này không ổn lắm nhé

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +        if (filter.coler != "cham de chon") {
cái "cham de chon" kìa là textholder thôi chứ nhỉ

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +        rcv?.adapter = ProductsAdapter(sortListWithSize, { productItemClick(it,view) })
gán 1 thằng adapter cho recyclerview ở bên ngoài rồi ở đây thay đổi items của adapter xong notifyDataSetChanged thôi

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +            btnItemCount.let {
thêm 1 dòng .let này hơi thừa

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +            val btnItemCount = view.findViewById<Button>(R.id.btnItemCount)
findView cho ra ngoài setOnClick nhé

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +                    bundleOf("items" to productsSelected)
tạo constant key

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +        }
```suggestion
        for (data in fakeData) {
            if (data.name.contains(string.uppercase(), true) || data.id.contains(string.uppercase(), true)) {
                list.add(data)
            }
        }
```

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +        (rcv?.adapter)?.notifyDataSetChanged()
khởi tạo adapter cho recyclerView 1 lần thôi ông, những lần sau chỉ notifyDataSetChanged thôi

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +        adapter.notifyDataSetChanged()
không cần

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +        bottomSheetView = LayoutInflater.from(requireContext()).inflate(
không tạo thằng `bottomSheetView` này thành biến chung nhé, để trong hàm này thôi

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +    private fun changeItemAmount() {
xử lý hàm này bên trên luôn cũng được

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +            btnItemCount.let {
.let ở đây thừa nhé

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +            btnTotalPrice.let {
tương tự

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/ShipFragment.kt
> +        val adpter = ReceiverViewAdapter(list,{})
callback ra ngoài không xử lý gì à ông

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/ShipFragment.kt
> +        adpter.notifyDataSetChanged()
mấy chỗ này tương tự, t không nhắc lại nữa nhé

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/fragments/ShipInforFragment.kt
> +            activity?.onBackPressed()
bấm Save chỉ back thôi nghĩa là khi thay đổi, chưa bấm Save đã lưu hết lại rồi hả

2022-03-16 09:21 UTC, B-0625 commented on app/src/main/java/com/misa/fresher/viewModel/ShareViewModel.kt
> +class ShareViewModel:ViewModel() {
Đặt tên tường minh hơn nhé

2022-03-16 09:27 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/ShipFragment.kt
> +        val adpter = ReceiverViewAdapter(list,{})
phần này chưa làm xong nên tôi để thế

2022-03-16 09:29 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/ShipInforFragment.kt
> +            activity?.onBackPressed()
bên kia khi mà cái ed thay đổi thì nó sẽ add cái text đấy vào view model luôn xong chỗ này tôi để chỉ check xem các trường nhập đủ không thôi, mà do tôi chưa kịp làm cái check nên nó thế

2022-03-16 09:31 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/adapters/ReceiverViewAdapter.kt
> +                clickView(item)
bên màn receiverFragment tôi có cái rcv, khi mà cái text chỗ này change thì thôi gọi cái hàm getData lấy cái text xong gửi nó vào viewmodel

2022-03-16 10:02 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/BillDetailFragment.kt
> +            activity?.onBackPressed()
có ông, hôm qua tôi xem lại thì cái tôi chuyền nó là cái tham chiếu thôi nên sửa bên này nó vẫn cập nhật

2022-03-16 10:02 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/RecipientFragment.kt
> +        it as ShippingView.TouchTextView
cái shippingView là sealed class, tôi muôn lấy cái thằng class bên trong để làm tiếp

2022-03-16 10:02 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/RecipientFragment.kt
> +        }
chỗ này tôi mới nghĩ đến cách này thôi, để t nghiên cứu thêm

2022-03-16 10:29 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/adapters/ProductSelectedAdapter.kt
> +                tvAmount.text = selectedProducts.amonut.toString()
chỗ này tôi vẫn chưa ok lắm. tôi để notify rồi mà nó không bind lại

2022-03-16 10:29 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/BillDetailFragment.kt
> +    var viewModel: ShareViewModel?= null
chỗ này tôi dùng cái lazy không đc nên tôi để thế

2022-03-16 10:29 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/BillsFragment.kt
> +            val adapter = BillsAdapter(it)
làm thế thì có vấn đề gì không ông

2022-03-17 01:53 UTC, BaoNguyen068 commented on app/src/main/java/com/misa/fresher/fragments/SaleFragment.kt
> +        if (filter.coler != "cham de chon") {
cái này hình như nó không có cái hint nên tôi chơi luôn cái cham de chon là 1 cái phần tử, xong xử lý.

2022-03-17 15:54 UTC, merged